################################################################################
##                          config file RNAseq pipeline                       ##
################################################################################

# set True or False
run_modes:
  STAR: True
  counts: False
  kallisto: False
  mixcr: True
  QCs: True

# additional arguments for snakemake
snakemake_arg: "-k"

# format names fastq files:
# [sample_name][read_name].fastq.gz

# Sample names
# sample_ID as header
samples: "/DATA/j.traets/Pipelines/RNAseq_snakemake_pipeline_v2_1/paired_test.txt"

# bam as input: True or False
bam_to_fastq_r: False

# read name, R1 + R2
# or in case of single reads, R1 only
read_name:
  R1: ".1"
  R2: ".2"
#_R1_001
#_R2_001

## params tools ##
STAR:
  threads: 10
  reference: "/DATA/j.traets/Reference_files/homo_sapiens/GRCh38_ensembl_105_primary/"
  mode: "--twopassMode Basic --outReadsUnmapped None"
  param_sam: "--chimSegmentMin 12 --chimJunctionOverhangMin 12 --alignSJDBoverhangMin 10 --alignMatesGapMax 100000 --alignIntronMax 100000 --chimSegmentReadGapMax parameter 3"
  other:  "--alignSJstitchMismatchNmax 5 -1 5 5 --limitBAMsortRAM 31532137230 --outSAMtype BAM SortedByCoordinate --readFilesCommand zcat --outSAMattributes NM"

ngsderive:
  reference: "/DATA/j.traets/Reference_files/homo_sapiens/GRCh38_ensembl_105_primary/Homo_sapiens.GRCh38.105.gtf"

HTSeq:
  reference: "/DATA/j.traets/Reference_files/homo_sapiens/GRCh38_ensembl_105_primary/Homo_sapiens.GRCh38.105.gtf"
  params: "-m intersection-nonempty -a 10"

kallisto:
  threads: 10
  reference: "/DATA/j.traets/Reference_files/homo_sapiens/Kallisto_reference_hg38/homo_sapiens/transcriptome.idx"

rsem:
  python_folder: "/DATA/j.traets/Pipelines/RNAseq_snakemake_pipeline_v1_2/"

MiXCR:
  jar_MiXCR: "/DATA/j.traets/Tools/MiXCR/mixcr.jar"
  jar_vdjtools: "/DATA/j.traets/Tools/vdjtools/vdjtools-1.2.1/vdjtools-1.2.1.jar"


## .sif containers ##
SIF:
  fastqc: "sif/fastqc_v0.11.9_cv8.sif" # fastqc
  htseq: "sif/htseq_v2.0.2_quay.sif" # htseq
  kallisto: "sif/kallisto_v0.48.0_zlskidmore.sif" # kallisto
  multiqc: "sif/multiqc_1.8_staphb.sif" # multiqc
  ngsderive: "sif/ngsderive_v1.2.0_stjudecloud.sif" # ngsderive
  samtools: "sif/samtools_1.9_staphb.sif" # samtools
  STAR: "sif/star-aligner_2.7.9a_danielfsribeiro.sif" # STAR
# sif containers can be changed manually

